### ISSUE TITLE
Android TV Support

### ISSUE THREAD

**Issue by joshjryan** [fredrikburmester/streamyfin#136] opened 2024-09-26 13:14 UTC
Requesting an Android TV version to be considered for v2.0+.

**Comment by retardgerman** [comment] 2024-09-26 13:39
Duplicate of #137

**Closed by retardgerman** 2024-09-26 13:39 UTC
Labels: ✨ enhancement

**Comment by joshjryan** [comment] 2024-09-26 14:11
Apologies for not not noticing the existing request. I searched the string "Android TV" and didn't return any results :)

**Comment by retardgerman** [comment] 2024-09-26 14:14
No worries! We had an internal discussion about merging all "TV related" issues into one. You did nothing wrong.
