### ISSUE TITLE
Add setting to select downloaded Media location (Internal/SD card)

### ISSUE THREAD

**Issue by Julian-1-2-3-4-5** [fredrikburmester/streamyfin#53] opened 2024-08-16 12:52 UTC
**Describe the solution you'd like**
I would love to have a setting be added to the app that lets one select a folder or at least between Internal or an SD Card, where Media will be downloaded to

**Comment by fredrikburmester** [comment] 2024-08-16 19:32
Unfortunately not on iOS it's not possible to download to a specified location on the device. We can, however, share the file from the app via the phones share sheet and from there add it to the phone storage. 

On android it might be possible, i'll look into it!

**Comment by fredrikburmester** [comment] 2024-08-16 19:39
duplicate of #42

**Closed by fredrikburmester** 2024-08-16 19:39 UTC
Labels: enhancement
