### ISSUE TITLE
apple tv & google tv

### ISSUE THREAD

**Issue by javierzhang0504** [fredrikburmester/streamyfin#253] opened 2024-12-06 01:17 UTC
Really like this app !
Do you have any plans to make a TV Box version ?
Apple TV and Android TV

**Comment by retardgerman** [comment] 2024-12-06 05:32
Yes we do, although it's not a top priority right now. 

Duplicate of #137

**Comment by retardgerman** [comment] 2024-12-06 05:32
Duplicate of #137

**Closed** 2024-12-06 05:34 UTC
Labels: ✨ enhancement
