### ISSUE TITLE
[Feature] Android TV Support

### ISSUE THREAD

**Issue by xcaliber93** [fredrikburmester/streamyfin#33] opened 2024-08-13 13:59 UTC
This would be a great upgrade over the Android TV version of the Jellyfin App.

Don't know how easy it is but if it can play 4K, DV, Atmos and all that natively on my TV without requiring an external app, it would be great

**Comment by 2IkHLHB** [comment] 2024-08-17 00:11
+1 for Android TV support.

**Comment by Sammeeeeeeee** [comment] 2024-08-18 13:55
+1, there is no alternative option rn to the official client, which I have found to be super buggy

**Comment by KomGiann** [comment] 2024-09-19 12:33
Is there any updates on this? I wanna add that native client have enormous music experience issues . Basically not an option to listen to music except hardly finding  and playing one song once a month

**Comment by retardgerman** [comment] 2024-09-26 13:41
Duplicate of #137

**Closed by retardgerman** 2024-09-26 13:41 UTC
