### ISSUE TITLE
[Bug]: text based subtitles don't show up in downloads

### ISSUE THREAD

**Issue by the-math-god** [fredrikburmester/streamyfin#277] opened 2024-12-10 21:53 UTC
### What happened?

pretty simple anytime i download a movie or show that uses text based subtitles
I.E. ass or srt 

the subtitles will not appear in the download even at max quality selected
this is present on any version streamyfin i've tried

### Reproduction steps

1. start the app
2. go to any movie or show that uses ass or srt subtitles
3. download it at any setting selected

### Which device and operating system are you using?

Device: [iphone SE]
OS: [iOS 18]

### Version

0.22.0

**Comment by Alexk2309** [comment] 2024-12-11 17:34
Duplicate of #240

**Closed by Alexk2309** 2024-12-11 17:34 UTC
Labels: ❌ bug
