### ISSUE TITLE
Issue with Logging into Jellyfin Server

### ISSUE THREAD

**Issue by Not-oss** [fredrikburmester/streamyfin#9] opened 2024-08-12 17:33 UTC
Hey, When i try to log into my Jellyfin server by entering the IP and port, it immediately prompts me for my username and password. After filling in the credentials and pressing the login button, nothing happens. There is no error message

**Comment by Not-oss** [comment] 2024-08-12 17:34
Also im on iOS 17.5.1 on an iPhone 12

**Comment by CalebWest2** [comment] 2024-08-12 17:35
I am having this same issue. I am on the latest iOS 18 beta

**Comment by fredrikburmester** [comment] 2024-08-12 17:36
I just released an update that should give a bit more into, please check TestFlight for version 0.2.1 (1).  @CalebWest2  @Not-oss

**Comment by Not-oss** [comment] 2024-08-12 17:40
Now i get the « A network error occured. Did you enter the correct server url? ». But i guess i found out why, i didnt see you needed to be on the same network as the remote, i connected with OpenVPN to remote and logged in on Streamify and everything worked. My fault for not reading😅

**Comment by CalebWest2** [comment] 2024-08-12 17:57
Does this work with Tailscale? Now it isn’t doing nothing like it was, but it is giving me the “wrong url” error. I am using the Tailscale VPN to access it remotely

**Comment by Not-oss** [comment] 2024-08-12 17:59
> Does this work with Tailscale? Now it isn’t doing nothing like it was, but it is giving me the “wrong url” error. I am using the Tailscale VPN to access it remotely

I really dont know but maybe you used the public ip instead of the local one. In my case i needed to put 10.0.0.45:8096 for it to work. Can’t help you more than that sorry

**Comment by voc0der** [comment] 2024-08-12 20:07
I dont want to make yet another thread for this, but logging in via `Quick Code` is a greatly desired feature that's missing here. That would help people wait until OIDC is implemented.

**Comment by fredrikburmester** [comment] 2024-08-13 07:14
duplicate of #16 #12 #7

**Closed by fredrikburmester** 2024-08-13 07:14 UTC
