### ISSUE TITLE
Apple TV support

### ISSUE THREAD

**Issue by Zegorax** [fredrikburmester/streamyfin#66] opened 2024-08-18 16:30 UTC
Ciao, hope you're doing well!

Would it be possible to release it as an Apple TV bundle as well?

Thanks a lot in advance!

**Comment by retardgerman** [comment] 2024-08-18 17:03
Hey!

Thanks for your idea! We are already working in the background to support more clients!

**Comment by 2600box** [comment] 2024-08-23 08:38
Just wanted to say that if a barebones TestFlight build for AppleTV is possible, it would be highly appreciated.

**Comment by retardgerman** [comment] 2024-09-26 13:42
Duplicate of #137

**Closed by retardgerman** 2024-09-26 13:42 UTC
Labels: ✨ enhancement, on-hold

**Comment by Darknior** [comment] 2025-09-27 17:21
I m dream about this feature too, with all my family we reading films on TV, my friends too ... and not on our phone :(
For now we can't use Streamyfin :(
And the official Jellyfin TV app is so boring and limited :(
Thanks for all your work <3

**Comment by Simon-Eklundh** [comment] 2025-09-27 17:24
We're currently a bit blocked by some dependencies but are hoping to get it working in a while

**Comment by Darknior** [comment] 2025-09-27 18:42
Thanks for your message :)
